name: "name upper is hello world Workflow"

on:
  push:
     branches:
        - test
        
jobs:
    hello_world:
        runs-on: ubuntu-latest
        steps: 
            - name: "print current date"
              run: date